# Generated by Django 5.1.4 on 2025-01-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
