# Generated by Django 5.1.4 on 2025-01-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_attachment_remove_answer_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='attachments',
        ),
        migrations.AddField(
            model_name='answer',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
