# Generated by Django 5.1.4 on 2025-01-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_question_attachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.answer'),
        ),
    ]
