# Generated by Django 5.1.4 on 2025-01-23 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_attachment_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attachments', to='main.answer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attachments', to='main.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
