# Generated by Django 5.1.4 on 2025-01-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_answerattachment_questionattachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattachment',
            name='question',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.question')),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerAttachment',
        ),
        migrations.DeleteModel(
            name='QuestionAttachment',
        ),
    ]
