# Generated by Django 5.1.4 on 2025-01-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_questionattachment_question_attachment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='QuestionAttachment',
        ),
    ]
