# Generated by Django 5.1.4 on 2025-01-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_commentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_distribution',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
