# Generated by Django 5.1.4 on 2025-01-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_email_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_distribution',
        ),
    ]
