# Generated by Django 5.1.4 on 2025-02-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='referenceform',
            field=models.TextField(blank=True),
        ),
    ]
